version: '3.8'

services:
  # SonarQube сервер
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - sonar-db
    networks:
      - sonar-network

  # PostgreSQL для SonarQube
  sonar-db:
    image: postgres:13
    container_name: sonar-database
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-network

  # Анализатор кода
  sonar-analyzer:
    image: gradle:8.5-jdk17
    container_name: sonar-analyzer
    working_dir: /app
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=squ_47bce0deb9f4aa76523c0609bae2b8e7d0272903
      - SONAR_PROJECT_KEY=devops:DevOps
      - GITHUB_REPO=https://github.com/Abuzer337/Devops4.git
      - TELEGRAM_BOT_TOKEN=8214582880:AAFnIB94F9bH-m6SNRNR9ktGph5lGW_ZSZs
      - TELEGRAM_CHAT_ID=931340901
    volumes:
      - ./sonar-analysis.sh:/app/sonar-analysis.sh:ro
      - gradle_cache:/root/.gradle
    command: /app/sonar-analysis.sh
    depends_on:
      - sonarqube
    networks:
      - sonar-network
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  gradle_cache:

networks:
  sonar-network:
    driver: bridge
